version: '3.4'
services:
  proxy:
    image: envoyproxy/envoy:v1.16.0
    container_name: webclient_envoy
    ports:
      - '8000:8000'
    volumes:
      - ${ENVOY_DEV_CONFIG}:/etc/envoy/envoy.yaml # absolute path to yaml file in ENVOY_CONFIG
    networks:
      - haaukins-webclient
    env_file:
      - .env

  webclient:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: build-stage
    networks:
      - haaukins-webclient
    env_file:
      - .env

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - '8003:8003'
    volumes:
      - ${CERTIFICATES_PATH}:/etc/certs
    networks:
      - haaukins-webclient
    env_file:
      - .env

# webclient .env file should consist VUE_APP_SLACK_API_KEY value
# in order to get notification through slack

networks:
  haaukins-webclient:

