version: '3.4'
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ${CERTIFICATES_PATH}:/etc/certs
    networks:
      - haaukins-webclient
    env_file:
      - .env

  webclient:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: build-stage
    networks:
      - haaukins-webclient
    ports:
    - '8003:8003'
    env_file:
      - .env

# webclient .env file should consist VUE_APP_SLACK_API_KEY value
# in order to get notification through slack

networks:
  haaukins-webclient:

