name: Build and  Publish Docker
on:
  push:
    tags: v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Envoy
        run: docker build . --file ./envoy/Dockerfile --tag envoy:${GITHUB_REF:10}
      - name: Tag build image with github registery
        run: docker tag envoy:${GITHUB_REF:10} docker.pkg.github.com/aau-network-security/haaukins-webclient/envoy:${GITHUB_REF:10}
      - name: Push envoy to github docker registery
        run: docker push docker.pkg.github.com/aau-network-security/haaukins-webclient/envoy:${GITHUB_REF:10}
